# Build settings
theme: minima

title: "Daniel D Stuart"

timezone: America/Los_Angeles

header_pages:
  - Projects.md
  - Publications.md

author :
	  name : Daniel D Stuart
	  email : daniel.d.stuart1@gmail.com
	  github : danieldstuart
